## Deprecated: Local Postgres via Docker Compose
# This project now uses Neon (managed PostgreSQL) by default.
# If you need a local Postgres for development, you can restore the previous
# contents from git history or set up Postgres manually.

# To use Neon, set DATABASE_URL in services/supervision_module/.env, e.g.:
# DATABASE_URL=postgresql://<user>:<password>@<host>.neon.tech/<db>?sslmode=require
